export default {
    name:'workExperience',
    title:'Work Experience',
    type:'document',
    fields:[
           {name:'name',
               title:'name',
               type:'string'
            },
            {
                name:'company',
                title:'Company',
                type:'string'
            },
            {
                name:'desc0',
                title:'Desc0',
                type:'string'
            },
            {
                name:'desc1',
                title:'Desc1',
                type:'string'
            },
            {
                name:'desc2',
                title:'Desc2',
                type:'string'
            },
            {
                name:'desc3',
                title:'Desc3',
                type:'string'
            },
            {
                name:'desc4',
                title:'Desc4',
                type:'string'
            },
            {
                name:'desc5',
                title:'Desc5',
                type:'string'
            }
    ],
   
}